### ISSUE TITLE
Silently complete fontawesome icon name

### ISSUE THREAD

**Issue by Cwpute** [askvortsov1/flarum-categories#47]
Why ask the user to always append `fas fa-` to the start of an icon name ? Requiring them to do so addsunnecessary typing and frustration if they somehow mess up the prefix.
The user should not have to worry about it and only append the icon's name, while `fas fa-` is automatically and silently added to it.

**Comment by Yippy** [comment]
The reason you have full icon name, just like extension Tags edit icon function. Is because you can choose between Solid, Regular, Light (Pro License), Dutone (Pro License).

![image](https://github.com/askvortsov1/flarum-categories/assets/6518915/8fe8cfab-7fbb-4497-b045-1a2f77b69d77)

![image](https://github.com/askvortsov1/flarum-categories/assets/6518915/564c9a04-b070-40af-a08c-7346b572f3fb)

![image](https://github.com/askvortsov1/flarum-categories/assets/6518915/65b4078d-45ca-4675-be2a-3cd819392f8b)

Though this isn't a bug for this extension, you should post the issue on flarum.
[flarum-categories](https://github.com/askvortsov1/flarum-categories) Doesn't amend Tag Icon names, it only displays them.

**Comment by Cwpute** [comment]
Hmm, the reason why i reported this was probably because Regular and Light icwns wouldn't work on my (old and dying) device.
But just like i noted in my other issue, i'm not using Flarum nor that computer anymore so this issue might as well be closed afaic.

Le 15 avril 2024 13:30:04 GMT+02:00, Yippy ***@***.***> a écrit :

**Comment by askvortsov1** [comment]
Agree that if we build something like this, it shouldn't be in this extension. But also I'm not convinced that this is needed with the preview.
